import type { CityNetwork } from "./types";

const barcelonaCore: CityNetwork = {
  cityId: "barcelona-core",
  cityName: "Barcelona Core",
  description: "Dense cultural graph with mixed transit and walking tradeoffs across central Barcelona.",
  defaultStartNodeId: "bcn-hotel",
  nodes: [
    {
      id: "bcn-hotel",
      cityId: "barcelona-core",
      name: "Passeig Hub Hotel",
      description: "Central origin node used as the route start for the optimization scenario.",
      kind: "origin",
      coordinate: { lat: 41.391, lng: 2.1649 },
      visitDurationMin: 0,
      priority: 1,
      baseScore: 1,
      tags: ["origin", "logistics"],
      timeWindows: [{ startMin: 8 * 60, endMin: 21 * 60, label: "All day" }],
    },
    {
      id: "sagrada-familia",
      cityId: "barcelona-core",
      name: "Sagrada Familia",
      description: "High-priority landmark with a fixed daytime availability window.",
      kind: "attraction",
      coordinate: { lat: 41.4036, lng: 2.1744 },
      visitDurationMin: 90,
      priority: 10,
      baseScore: 9,
      tags: ["architecture", "iconic", "history"],
      timeWindows: [{ startMin: 9 * 60, endMin: 17 * 60, label: "Ticketed entry" }],
    },
    {
      id: "park-guell",
      cityId: "barcelona-core",
      name: "Park Guell",
      description: "Scenic hilltop stop with stronger payoff for scenic preference weighting.",
      kind: "attraction",
      coordinate: { lat: 41.4145, lng: 2.1527 },
      visitDurationMin: 75,
      priority: 8,
      baseScore: 8,
      tags: ["scenic", "architecture", "outdoors"],
      timeWindows: [{ startMin: 9 * 60 + 30, endMin: 18 * 60, label: "Park access" }],
    },
    {
      id: "picasso-museum",
      cityId: "barcelona-core",
      name: "Picasso Museum",
      description: "Art-focused node that becomes more attractive under museum-heavy preferences.",
      kind: "attraction",
      coordinate: { lat: 41.3853, lng: 2.1804 },
      visitDurationMin: 80,
      priority: 7,
      baseScore: 7,
      tags: ["art", "museum", "history"],
      timeWindows: [{ startMin: 10 * 60, endMin: 18 * 60, label: "Gallery hours" }],
    },
    {
      id: "boqueria-market",
      cityId: "barcelona-core",
      name: "La Boqueria",
      description: "Food-oriented node with a midday window and shorter dwell time.",
      kind: "food",
      coordinate: { lat: 41.3818, lng: 2.1715 },
      visitDurationMin: 50,
      priority: 6,
      baseScore: 6,
      tags: ["food", "market", "local"],
      timeWindows: [{ startMin: 10 * 60, endMin: 15 * 60, label: "Market hours" }],
    },
    {
      id: "gothic-quarter",
      cityId: "barcelona-core",
      name: "Gothic Quarter",
      description: "Flexible old-city waypoint with long availability and moderate priority.",
      kind: "attraction",
      coordinate: { lat: 41.3839, lng: 2.1763 },
      visitDurationMin: 60,
      priority: 7,
      baseScore: 6,
      tags: ["history", "walk", "architecture"],
      timeWindows: [{ startMin: 9 * 60, endMin: 20 * 60, label: "Open district" }],
    },
    {
      id: "montjuic",
      cityId: "barcelona-core",
      name: "Montjuic Cable Area",
      description: "Transit-heavy scenic node whose value depends on traffic-like edge latency.",
      kind: "attraction",
      coordinate: { lat: 41.3632, lng: 2.1651 },
      visitDurationMin: 70,
      priority: 6,
      baseScore: 7,
      tags: ["scenic", "outdoors", "viewpoint"],
      timeWindows: [{ startMin: 10 * 60, endMin: 19 * 60, label: "Daylight operations" }],
    },
    {
      id: "barceloneta",
      cityId: "barcelona-core",
      name: "Barceloneta Waterfront",
      description: "Flexible low-friction node that is useful when other attractions close.",
      kind: "attraction",
      coordinate: { lat: 41.3758, lng: 2.1925 },
      visitDurationMin: 55,
      priority: 5,
      baseScore: 5,
      tags: ["scenic", "walk", "waterfront"],
      timeWindows: [{ startMin: 9 * 60, endMin: 21 * 60, label: "Open district" }],
    },
  ],
  edges: [
    { id: "b1", from: "bcn-hotel", to: "sagrada-familia", mode: "walk", distanceMeters: 1800, baseTravelTimeMin: 14 },
    { id: "b2", from: "bcn-hotel", to: "gothic-quarter", mode: "walk", distanceMeters: 1700, baseTravelTimeMin: 16 },
    { id: "b3", from: "bcn-hotel", to: "park-guell", mode: "transit", distanceMeters: 3200, baseTravelTimeMin: 18 },
    { id: "b4", from: "sagrada-familia", to: "park-guell", mode: "transit", distanceMeters: 2600, baseTravelTimeMin: 15 },
    { id: "b5", from: "sagrada-familia", to: "picasso-museum", mode: "transit", distanceMeters: 3000, baseTravelTimeMin: 17 },
    { id: "b6", from: "picasso-museum", to: "gothic-quarter", mode: "walk", distanceMeters: 700, baseTravelTimeMin: 8 },
    { id: "b7", from: "gothic-quarter", to: "boqueria-market", mode: "walk", distanceMeters: 500, baseTravelTimeMin: 6 },
    { id: "b8", from: "gothic-quarter", to: "barceloneta", mode: "walk", distanceMeters: 1500, baseTravelTimeMin: 14 },
    { id: "b9", from: "barceloneta", to: "picasso-museum", mode: "walk", distanceMeters: 1400, baseTravelTimeMin: 13 },
    { id: "b10", from: "boqueria-market", to: "montjuic", mode: "transit", distanceMeters: 2400, baseTravelTimeMin: 18 },
    { id: "b11", from: "park-guell", to: "montjuic", mode: "transit", distanceMeters: 5600, baseTravelTimeMin: 28 },
    { id: "b12", from: "montjuic", to: "barceloneta", mode: "transit", distanceMeters: 4300, baseTravelTimeMin: 22 },
    { id: "b13", from: "boqueria-market", to: "picasso-museum", mode: "walk", distanceMeters: 1100, baseTravelTimeMin: 10 },
  ],
};

const tokyoCircuit: CityNetwork = {
  cityId: "tokyo-circuit",
  cityName: "Tokyo Circuit",
  description: "Transit-dominant city graph with strong time-window interactions across east and west Tokyo.",
  defaultStartNodeId: "tokyo-station-hotel",
  nodes: [
    {
      id: "tokyo-station-hotel",
      cityId: "tokyo-circuit",
      name: "Tokyo Station Hotel",
      description: "Origin node near the city rail network core.",
      kind: "origin",
      coordinate: { lat: 35.6812, lng: 139.7671 },
      visitDurationMin: 0,
      priority: 1,
      baseScore: 1,
      tags: ["origin", "logistics"],
      timeWindows: [{ startMin: 8 * 60, endMin: 22 * 60 }],
    },
    {
      id: "sensoji",
      cityId: "tokyo-circuit",
      name: "Senso-ji",
      description: "Historic east-side anchor with long hours and strong cultural weight.",
      kind: "attraction",
      coordinate: { lat: 35.7148, lng: 139.7967 },
      visitDurationMin: 75,
      priority: 9,
      baseScore: 8,
      tags: ["history", "temple", "culture"],
      timeWindows: [{ startMin: 9 * 60, endMin: 18 * 60 }],
    },
    {
      id: "akihabara",
      cityId: "tokyo-circuit",
      name: "Akihabara",
      description: "Flexible electronics corridor with moderate value and late closing.",
      kind: "attraction",
      coordinate: { lat: 35.6984, lng: 139.773 },
      visitDurationMin: 60,
      priority: 6,
      baseScore: 6,
      tags: ["technology", "shopping", "walk"],
      timeWindows: [{ startMin: 10 * 60, endMin: 21 * 60 }],
    },
    {
      id: "tsukiji",
      cityId: "tokyo-circuit",
      name: "Tsukiji Outer Market",
      description: "Food-heavy location that becomes infeasible later in the day.",
      kind: "food",
      coordinate: { lat: 35.6655, lng: 139.7708 },
      visitDurationMin: 55,
      priority: 7,
      baseScore: 7,
      tags: ["food", "market", "local"],
      timeWindows: [{ startMin: 8 * 60 + 30, endMin: 14 * 60, label: "Market hours" }],
    },
    {
      id: "teamlab",
      cityId: "tokyo-circuit",
      name: "teamLab Planets",
      description: "Ticketed art stop whose score rises sharply for immersive-art preferences.",
      kind: "attraction",
      coordinate: { lat: 35.6499, lng: 139.7899 },
      visitDurationMin: 90,
      priority: 8,
      baseScore: 8,
      tags: ["art", "museum", "immersive"],
      timeWindows: [{ startMin: 10 * 60, endMin: 20 * 60 }],
    },
    {
      id: "shibuya",
      cityId: "tokyo-circuit",
      name: "Shibuya Crossing",
      description: "Late-day flexible node that is resilient to mid-route disruptions.",
      kind: "attraction",
      coordinate: { lat: 35.6595, lng: 139.7005 },
      visitDurationMin: 50,
      priority: 6,
      baseScore: 6,
      tags: ["urban", "nightlife", "walk"],
      timeWindows: [{ startMin: 10 * 60, endMin: 22 * 60 }],
    },
    {
      id: "meiji-jingu",
      cityId: "tokyo-circuit",
      name: "Meiji Jingu",
      description: "Large green-space node that competes well when scenic weighting dominates.",
      kind: "attraction",
      coordinate: { lat: 35.6764, lng: 139.6993 },
      visitDurationMin: 70,
      priority: 7,
      baseScore: 7,
      tags: ["scenic", "history", "outdoors"],
      timeWindows: [{ startMin: 9 * 60, endMin: 18 * 60 + 30 }],
    },
    {
      id: "ueno",
      cityId: "tokyo-circuit",
      name: "Ueno Park Museums",
      description: "Museum cluster with moderate urgency and east-side proximity.",
      kind: "attraction",
      coordinate: { lat: 35.7156, lng: 139.7745 },
      visitDurationMin: 80,
      priority: 7,
      baseScore: 7,
      tags: ["museum", "art", "scenic"],
      timeWindows: [{ startMin: 9 * 60 + 30, endMin: 17 * 60 + 30 }],
    },
  ],
  edges: [
    { id: "t1", from: "tokyo-station-hotel", to: "akihabara", mode: "transit", distanceMeters: 2200, baseTravelTimeMin: 10 },
    { id: "t2", from: "tokyo-station-hotel", to: "tsukiji", mode: "transit", distanceMeters: 1700, baseTravelTimeMin: 9 },
    { id: "t3", from: "tokyo-station-hotel", to: "sensoji", mode: "transit", distanceMeters: 4500, baseTravelTimeMin: 18 },
    { id: "t4", from: "akihabara", to: "ueno", mode: "walk", distanceMeters: 2200, baseTravelTimeMin: 17 },
    { id: "t5", from: "ueno", to: "sensoji", mode: "transit", distanceMeters: 2600, baseTravelTimeMin: 11 },
    { id: "t6", from: "tsukiji", to: "teamlab", mode: "transit", distanceMeters: 2600, baseTravelTimeMin: 12 },
    { id: "t7", from: "teamlab", to: "shibuya", mode: "transit", distanceMeters: 8600, baseTravelTimeMin: 25 },
    { id: "t8", from: "shibuya", to: "meiji-jingu", mode: "walk", distanceMeters: 1700, baseTravelTimeMin: 15 },
    { id: "t9", from: "akihabara", to: "shibuya", mode: "transit", distanceMeters: 9300, baseTravelTimeMin: 27 },
    { id: "t10", from: "tsukiji", to: "shibuya", mode: "transit", distanceMeters: 7600, baseTravelTimeMin: 23 },
    { id: "t11", from: "ueno", to: "tokyo-station-hotel", mode: "transit", distanceMeters: 3900, baseTravelTimeMin: 16 },
    { id: "t12", from: "meiji-jingu", to: "tokyo-station-hotel", mode: "transit", distanceMeters: 6900, baseTravelTimeMin: 22 },
  ],
};

export const CITY_NETWORKS: CityNetwork[] = [barcelonaCore, tokyoCircuit];

export const ROUTE_ENGINE_CITY_CATALOG = CITY_NETWORKS.map((network) => ({
  cityId: network.cityId,
  cityName: network.cityName,
  description: network.description,
  defaultStartNodeId: network.defaultStartNodeId,
  nodes: network.nodes.map((node) => ({
    id: node.id,
    name: node.name,
    kind: node.kind,
    tags: node.tags,
    priority: node.priority,
    visitDurationMin: node.visitDurationMin,
    timeWindows: node.timeWindows,
  })),
  edges: network.edges.length,
}));

export function getCityNetwork(cityId: string) {
  return CITY_NETWORKS.find((network) => network.cityId === cityId);
}
